/* 
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.Finances
{
    /// <summary>
    /// Contains all information related to a financial event.
    /// </summary>
    [DataContract]
    public partial class FinancialEvents : IEquatable<FinancialEvents>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FinancialEvents" /> class.
        /// </summary>
        /// <param name="ShipmentEventList">A list of shipment events..</param>
        /// <param name="RefundEventList">A list of refund events..</param>
        /// <param name="GuaranteeClaimEventList">A list of guarantee claim events..</param>
        /// <param name="ChargebackEventList">A list of chargeback events..</param>
        /// <param name="PayWithAmazonEventList">PayWithAmazonEventList.</param>
        /// <param name="ServiceProviderCreditEventList">ServiceProviderCreditEventList.</param>
        /// <param name="RetrochargeEventList">RetrochargeEventList.</param>
        /// <param name="RentalTransactionEventList">RentalTransactionEventList.</param>
        /// <param name="ProductAdsPaymentEventList">ProductAdsPaymentEventList.</param>
        /// <param name="ServiceFeeEventList">ServiceFeeEventList.</param>
        /// <param name="SellerDealPaymentEventList">SellerDealPaymentEventList.</param>
        /// <param name="DebtRecoveryEventList">DebtRecoveryEventList.</param>
        /// <param name="LoanServicingEventList">LoanServicingEventList.</param>
        /// <param name="AdjustmentEventList">AdjustmentEventList.</param>
        /// <param name="SAFETReimbursementEventList">SAFETReimbursementEventList.</param>
        /// <param name="SellerReviewEnrollmentPaymentEventList">SellerReviewEnrollmentPaymentEventList.</param>
        /// <param name="FBALiquidationEventList">FBALiquidationEventList.</param>
        /// <param name="CouponPaymentEventList">CouponPaymentEventList.</param>
        /// <param name="ImagingServicesFeeEventList">ImagingServicesFeeEventList.</param>
        /// <param name="NetworkComminglingTransactionEventList">NetworkComminglingTransactionEventList.</param>
        /// <param name="AffordabilityExpenseEventList">AffordabilityExpenseEventList.</param>
        /// <param name="AffordabilityExpenseReversalEventList">AffordabilityExpenseReversalEventList.</param>
        public FinancialEvents() { }
        public FinancialEvents(ShipmentEventList ShipmentEventList = default(ShipmentEventList), ShipmentEventList RefundEventList = default(ShipmentEventList), ShipmentEventList GuaranteeClaimEventList = default(ShipmentEventList), ShipmentEventList ChargebackEventList = default(ShipmentEventList), PayWithAmazonEventList PayWithAmazonEventList = default(PayWithAmazonEventList), SolutionProviderCreditEventList ServiceProviderCreditEventList = default(SolutionProviderCreditEventList), RetrochargeEventList RetrochargeEventList = default(RetrochargeEventList), RentalTransactionEventList RentalTransactionEventList = default(RentalTransactionEventList), ProductAdsPaymentEventList ProductAdsPaymentEventList = default(ProductAdsPaymentEventList), ServiceFeeEventList ServiceFeeEventList = default(ServiceFeeEventList), SellerDealPaymentEventList SellerDealPaymentEventList = default(SellerDealPaymentEventList), DebtRecoveryEventList DebtRecoveryEventList = default(DebtRecoveryEventList), LoanServicingEventList LoanServicingEventList = default(LoanServicingEventList), AdjustmentEventList AdjustmentEventList = default(AdjustmentEventList), SAFETReimbursementEventList SAFETReimbursementEventList = default(SAFETReimbursementEventList), SellerReviewEnrollmentPaymentEventList SellerReviewEnrollmentPaymentEventList = default(SellerReviewEnrollmentPaymentEventList), FBALiquidationEventList FBALiquidationEventList = default(FBALiquidationEventList), CouponPaymentEventList CouponPaymentEventList = default(CouponPaymentEventList), ImagingServicesFeeEventList ImagingServicesFeeEventList = default(ImagingServicesFeeEventList), NetworkComminglingTransactionEventList NetworkComminglingTransactionEventList = default(NetworkComminglingTransactionEventList), AffordabilityExpenseEventList AffordabilityExpenseEventList = default(AffordabilityExpenseEventList), AffordabilityExpenseEventList AffordabilityExpenseReversalEventList = default(AffordabilityExpenseEventList))
        {
            this.ShipmentEventList = ShipmentEventList;
            this.RefundEventList = RefundEventList;
            this.GuaranteeClaimEventList = GuaranteeClaimEventList;
            this.ChargebackEventList = ChargebackEventList;
            this.PayWithAmazonEventList = PayWithAmazonEventList;
            this.ServiceProviderCreditEventList = ServiceProviderCreditEventList;
            this.RetrochargeEventList = RetrochargeEventList;
            this.RentalTransactionEventList = RentalTransactionEventList;
            this.ProductAdsPaymentEventList = ProductAdsPaymentEventList;
            this.ServiceFeeEventList = ServiceFeeEventList;
            this.SellerDealPaymentEventList = SellerDealPaymentEventList;
            this.DebtRecoveryEventList = DebtRecoveryEventList;
            this.LoanServicingEventList = LoanServicingEventList;
            this.AdjustmentEventList = AdjustmentEventList;
            this.SAFETReimbursementEventList = SAFETReimbursementEventList;
            this.SellerReviewEnrollmentPaymentEventList = SellerReviewEnrollmentPaymentEventList;
            this.FBALiquidationEventList = FBALiquidationEventList;
            this.CouponPaymentEventList = CouponPaymentEventList;
            this.ImagingServicesFeeEventList = ImagingServicesFeeEventList;
            this.NetworkComminglingTransactionEventList = NetworkComminglingTransactionEventList;
            this.AffordabilityExpenseEventList = AffordabilityExpenseEventList;
            this.AffordabilityExpenseReversalEventList = AffordabilityExpenseReversalEventList;
        }

        /// <summary>
        /// A list of shipment events.
        /// </summary>
        /// <value>A list of shipment events.</value>
        [DataMember(Name = "ShipmentEventList", EmitDefaultValue = false)]
        public ShipmentEventList ShipmentEventList { get; set; }

        /// <summary>
        /// A list of refund events.
        /// </summary>
        /// <value>A list of refund events.</value>
        [DataMember(Name = "RefundEventList", EmitDefaultValue = false)]
        public ShipmentEventList RefundEventList { get; set; }

        /// <summary>
        /// A list of guarantee claim events.
        /// </summary>
        /// <value>A list of guarantee claim events.</value>
        [DataMember(Name = "GuaranteeClaimEventList", EmitDefaultValue = false)]
        public ShipmentEventList GuaranteeClaimEventList { get; set; }

        /// <summary>
        /// A list of chargeback events.
        /// </summary>
        /// <value>A list of chargeback events.</value>
        [DataMember(Name = "ChargebackEventList", EmitDefaultValue = false)]
        public ShipmentEventList ChargebackEventList { get; set; }

        /// <summary>
        /// Gets or Sets PayWithAmazonEventList
        /// </summary>
        [DataMember(Name = "PayWithAmazonEventList", EmitDefaultValue = false)]
        public PayWithAmazonEventList PayWithAmazonEventList { get; set; }

        /// <summary>
        /// Gets or Sets ServiceProviderCreditEventList
        /// </summary>
        [DataMember(Name = "ServiceProviderCreditEventList", EmitDefaultValue = false)]
        public SolutionProviderCreditEventList ServiceProviderCreditEventList { get; set; }

        /// <summary>
        /// Gets or Sets RetrochargeEventList
        /// </summary>
        [DataMember(Name = "RetrochargeEventList", EmitDefaultValue = false)]
        public RetrochargeEventList RetrochargeEventList { get; set; }

        /// <summary>
        /// Gets or Sets RentalTransactionEventList
        /// </summary>
        [DataMember(Name = "RentalTransactionEventList", EmitDefaultValue = false)]
        public RentalTransactionEventList RentalTransactionEventList { get; set; }

        /// <summary>
        /// Gets or Sets ProductAdsPaymentEventList
        /// </summary>
        [DataMember(Name = "ProductAdsPaymentEventList", EmitDefaultValue = false)]
        public ProductAdsPaymentEventList ProductAdsPaymentEventList { get; set; }

        /// <summary>
        /// Gets or Sets ServiceFeeEventList
        /// </summary>
        [DataMember(Name = "ServiceFeeEventList", EmitDefaultValue = false)]
        public ServiceFeeEventList ServiceFeeEventList { get; set; }

        /// <summary>
        /// Gets or Sets SellerDealPaymentEventList
        /// </summary>
        [DataMember(Name = "SellerDealPaymentEventList", EmitDefaultValue = false)]
        public SellerDealPaymentEventList SellerDealPaymentEventList { get; set; }

        /// <summary>
        /// Gets or Sets DebtRecoveryEventList
        /// </summary>
        [DataMember(Name = "DebtRecoveryEventList", EmitDefaultValue = false)]
        public DebtRecoveryEventList DebtRecoveryEventList { get; set; }

        /// <summary>
        /// Gets or Sets LoanServicingEventList
        /// </summary>
        [DataMember(Name = "LoanServicingEventList", EmitDefaultValue = false)]
        public LoanServicingEventList LoanServicingEventList { get; set; }

        /// <summary>
        /// Gets or Sets AdjustmentEventList
        /// </summary>
        [DataMember(Name = "AdjustmentEventList", EmitDefaultValue = false)]
        public AdjustmentEventList AdjustmentEventList { get; set; }

        /// <summary>
        /// Gets or Sets SAFETReimbursementEventList
        /// </summary>
        [DataMember(Name = "SAFETReimbursementEventList", EmitDefaultValue = false)]
        public SAFETReimbursementEventList SAFETReimbursementEventList { get; set; }

        /// <summary>
        /// Gets or Sets SellerReviewEnrollmentPaymentEventList
        /// </summary>
        [DataMember(Name = "SellerReviewEnrollmentPaymentEventList", EmitDefaultValue = false)]
        public SellerReviewEnrollmentPaymentEventList SellerReviewEnrollmentPaymentEventList { get; set; }

        /// <summary>
        /// Gets or Sets FBALiquidationEventList
        /// </summary>
        [DataMember(Name = "FBALiquidationEventList", EmitDefaultValue = false)]
        public FBALiquidationEventList FBALiquidationEventList { get; set; }

        /// <summary>
        /// Gets or Sets CouponPaymentEventList
        /// </summary>
        [DataMember(Name = "CouponPaymentEventList", EmitDefaultValue = false)]
        public CouponPaymentEventList CouponPaymentEventList { get; set; }

        /// <summary>
        /// Gets or Sets ImagingServicesFeeEventList
        /// </summary>
        [DataMember(Name = "ImagingServicesFeeEventList", EmitDefaultValue = false)]
        public ImagingServicesFeeEventList ImagingServicesFeeEventList { get; set; }

        /// <summary>
        /// Gets or Sets NetworkComminglingTransactionEventList
        /// </summary>
        [DataMember(Name = "NetworkComminglingTransactionEventList", EmitDefaultValue = false)]
        public NetworkComminglingTransactionEventList NetworkComminglingTransactionEventList { get; set; }

        /// <summary>
        /// Gets or Sets AffordabilityExpenseEventList
        /// </summary>
        [DataMember(Name = "AffordabilityExpenseEventList", EmitDefaultValue = false)]
        public AffordabilityExpenseEventList AffordabilityExpenseEventList { get; set; }

        /// <summary>
        /// Gets or Sets AffordabilityExpenseReversalEventList
        /// </summary>
        [DataMember(Name = "AffordabilityExpenseReversalEventList", EmitDefaultValue = false)]
        public AffordabilityExpenseEventList AffordabilityExpenseReversalEventList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FinancialEvents {\n");
            sb.Append("  ShipmentEventList: ").Append(ShipmentEventList).Append("\n");
            sb.Append("  RefundEventList: ").Append(RefundEventList).Append("\n");
            sb.Append("  GuaranteeClaimEventList: ").Append(GuaranteeClaimEventList).Append("\n");
            sb.Append("  ChargebackEventList: ").Append(ChargebackEventList).Append("\n");
            sb.Append("  PayWithAmazonEventList: ").Append(PayWithAmazonEventList).Append("\n");
            sb.Append("  ServiceProviderCreditEventList: ").Append(ServiceProviderCreditEventList).Append("\n");
            sb.Append("  RetrochargeEventList: ").Append(RetrochargeEventList).Append("\n");
            sb.Append("  RentalTransactionEventList: ").Append(RentalTransactionEventList).Append("\n");
            sb.Append("  ProductAdsPaymentEventList: ").Append(ProductAdsPaymentEventList).Append("\n");
            sb.Append("  ServiceFeeEventList: ").Append(ServiceFeeEventList).Append("\n");
            sb.Append("  SellerDealPaymentEventList: ").Append(SellerDealPaymentEventList).Append("\n");
            sb.Append("  DebtRecoveryEventList: ").Append(DebtRecoveryEventList).Append("\n");
            sb.Append("  LoanServicingEventList: ").Append(LoanServicingEventList).Append("\n");
            sb.Append("  AdjustmentEventList: ").Append(AdjustmentEventList).Append("\n");
            sb.Append("  SAFETReimbursementEventList: ").Append(SAFETReimbursementEventList).Append("\n");
            sb.Append("  SellerReviewEnrollmentPaymentEventList: ").Append(SellerReviewEnrollmentPaymentEventList).Append("\n");
            sb.Append("  FBALiquidationEventList: ").Append(FBALiquidationEventList).Append("\n");
            sb.Append("  CouponPaymentEventList: ").Append(CouponPaymentEventList).Append("\n");
            sb.Append("  ImagingServicesFeeEventList: ").Append(ImagingServicesFeeEventList).Append("\n");
            sb.Append("  NetworkComminglingTransactionEventList: ").Append(NetworkComminglingTransactionEventList).Append("\n");
            sb.Append("  AffordabilityExpenseEventList: ").Append(AffordabilityExpenseEventList).Append("\n");
            sb.Append("  AffordabilityExpenseReversalEventList: ").Append(AffordabilityExpenseReversalEventList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FinancialEvents);
        }

        /// <summary>
        /// Returns true if FinancialEvents instances are equal
        /// </summary>
        /// <param name="input">Instance of FinancialEvents to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FinancialEvents input)
        {
            if (input == null)
                return false;

            return
                (
                    this.ShipmentEventList == input.ShipmentEventList ||
                    (this.ShipmentEventList != null &&
                    this.ShipmentEventList.Equals(input.ShipmentEventList))
                ) &&
                (
                    this.RefundEventList == input.RefundEventList ||
                    (this.RefundEventList != null &&
                    this.RefundEventList.Equals(input.RefundEventList))
                ) &&
                (
                    this.GuaranteeClaimEventList == input.GuaranteeClaimEventList ||
                    (this.GuaranteeClaimEventList != null &&
                    this.GuaranteeClaimEventList.Equals(input.GuaranteeClaimEventList))
                ) &&
                (
                    this.ChargebackEventList == input.ChargebackEventList ||
                    (this.ChargebackEventList != null &&
                    this.ChargebackEventList.Equals(input.ChargebackEventList))
                ) &&
                (
                    this.PayWithAmazonEventList == input.PayWithAmazonEventList ||
                    (this.PayWithAmazonEventList != null &&
                    this.PayWithAmazonEventList.Equals(input.PayWithAmazonEventList))
                ) &&
                (
                    this.ServiceProviderCreditEventList == input.ServiceProviderCreditEventList ||
                    (this.ServiceProviderCreditEventList != null &&
                    this.ServiceProviderCreditEventList.Equals(input.ServiceProviderCreditEventList))
                ) &&
                (
                    this.RetrochargeEventList == input.RetrochargeEventList ||
                    (this.RetrochargeEventList != null &&
                    this.RetrochargeEventList.Equals(input.RetrochargeEventList))
                ) &&
                (
                    this.RentalTransactionEventList == input.RentalTransactionEventList ||
                    (this.RentalTransactionEventList != null &&
                    this.RentalTransactionEventList.Equals(input.RentalTransactionEventList))
                ) &&
                (
                    this.ProductAdsPaymentEventList == input.ProductAdsPaymentEventList ||
                    (this.ProductAdsPaymentEventList != null &&
                    this.ProductAdsPaymentEventList.Equals(input.ProductAdsPaymentEventList))
                ) &&
                (
                    this.ServiceFeeEventList == input.ServiceFeeEventList ||
                    (this.ServiceFeeEventList != null &&
                    this.ServiceFeeEventList.Equals(input.ServiceFeeEventList))
                ) &&
                (
                    this.SellerDealPaymentEventList == input.SellerDealPaymentEventList ||
                    (this.SellerDealPaymentEventList != null &&
                    this.SellerDealPaymentEventList.Equals(input.SellerDealPaymentEventList))
                ) &&
                (
                    this.DebtRecoveryEventList == input.DebtRecoveryEventList ||
                    (this.DebtRecoveryEventList != null &&
                    this.DebtRecoveryEventList.Equals(input.DebtRecoveryEventList))
                ) &&
                (
                    this.LoanServicingEventList == input.LoanServicingEventList ||
                    (this.LoanServicingEventList != null &&
                    this.LoanServicingEventList.Equals(input.LoanServicingEventList))
                ) &&
                (
                    this.AdjustmentEventList == input.AdjustmentEventList ||
                    (this.AdjustmentEventList != null &&
                    this.AdjustmentEventList.Equals(input.AdjustmentEventList))
                ) &&
                (
                    this.SAFETReimbursementEventList == input.SAFETReimbursementEventList ||
                    (this.SAFETReimbursementEventList != null &&
                    this.SAFETReimbursementEventList.Equals(input.SAFETReimbursementEventList))
                ) &&
                (
                    this.SellerReviewEnrollmentPaymentEventList == input.SellerReviewEnrollmentPaymentEventList ||
                    (this.SellerReviewEnrollmentPaymentEventList != null &&
                    this.SellerReviewEnrollmentPaymentEventList.Equals(input.SellerReviewEnrollmentPaymentEventList))
                ) &&
                (
                    this.FBALiquidationEventList == input.FBALiquidationEventList ||
                    (this.FBALiquidationEventList != null &&
                    this.FBALiquidationEventList.Equals(input.FBALiquidationEventList))
                ) &&
                (
                    this.CouponPaymentEventList == input.CouponPaymentEventList ||
                    (this.CouponPaymentEventList != null &&
                    this.CouponPaymentEventList.Equals(input.CouponPaymentEventList))
                ) &&
                (
                    this.ImagingServicesFeeEventList == input.ImagingServicesFeeEventList ||
                    (this.ImagingServicesFeeEventList != null &&
                    this.ImagingServicesFeeEventList.Equals(input.ImagingServicesFeeEventList))
                ) &&
                (
                    this.NetworkComminglingTransactionEventList == input.NetworkComminglingTransactionEventList ||
                    (this.NetworkComminglingTransactionEventList != null &&
                    this.NetworkComminglingTransactionEventList.Equals(input.NetworkComminglingTransactionEventList))
                ) &&
                (
                    this.AffordabilityExpenseEventList == input.AffordabilityExpenseEventList ||
                    (this.AffordabilityExpenseEventList != null &&
                    this.AffordabilityExpenseEventList.Equals(input.AffordabilityExpenseEventList))
                ) &&
                (
                    this.AffordabilityExpenseReversalEventList == input.AffordabilityExpenseReversalEventList ||
                    (this.AffordabilityExpenseReversalEventList != null &&
                    this.AffordabilityExpenseReversalEventList.Equals(input.AffordabilityExpenseReversalEventList))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShipmentEventList != null)
                    hashCode = hashCode * 59 + this.ShipmentEventList.GetHashCode();
                if (this.RefundEventList != null)
                    hashCode = hashCode * 59 + this.RefundEventList.GetHashCode();
                if (this.GuaranteeClaimEventList != null)
                    hashCode = hashCode * 59 + this.GuaranteeClaimEventList.GetHashCode();
                if (this.ChargebackEventList != null)
                    hashCode = hashCode * 59 + this.ChargebackEventList.GetHashCode();
                if (this.PayWithAmazonEventList != null)
                    hashCode = hashCode * 59 + this.PayWithAmazonEventList.GetHashCode();
                if (this.ServiceProviderCreditEventList != null)
                    hashCode = hashCode * 59 + this.ServiceProviderCreditEventList.GetHashCode();
                if (this.RetrochargeEventList != null)
                    hashCode = hashCode * 59 + this.RetrochargeEventList.GetHashCode();
                if (this.RentalTransactionEventList != null)
                    hashCode = hashCode * 59 + this.RentalTransactionEventList.GetHashCode();
                if (this.ProductAdsPaymentEventList != null)
                    hashCode = hashCode * 59 + this.ProductAdsPaymentEventList.GetHashCode();
                if (this.ServiceFeeEventList != null)
                    hashCode = hashCode * 59 + this.ServiceFeeEventList.GetHashCode();
                if (this.SellerDealPaymentEventList != null)
                    hashCode = hashCode * 59 + this.SellerDealPaymentEventList.GetHashCode();
                if (this.DebtRecoveryEventList != null)
                    hashCode = hashCode * 59 + this.DebtRecoveryEventList.GetHashCode();
                if (this.LoanServicingEventList != null)
                    hashCode = hashCode * 59 + this.LoanServicingEventList.GetHashCode();
                if (this.AdjustmentEventList != null)
                    hashCode = hashCode * 59 + this.AdjustmentEventList.GetHashCode();
                if (this.SAFETReimbursementEventList != null)
                    hashCode = hashCode * 59 + this.SAFETReimbursementEventList.GetHashCode();
                if (this.SellerReviewEnrollmentPaymentEventList != null)
                    hashCode = hashCode * 59 + this.SellerReviewEnrollmentPaymentEventList.GetHashCode();
                if (this.FBALiquidationEventList != null)
                    hashCode = hashCode * 59 + this.FBALiquidationEventList.GetHashCode();
                if (this.CouponPaymentEventList != null)
                    hashCode = hashCode * 59 + this.CouponPaymentEventList.GetHashCode();
                if (this.ImagingServicesFeeEventList != null)
                    hashCode = hashCode * 59 + this.ImagingServicesFeeEventList.GetHashCode();
                if (this.NetworkComminglingTransactionEventList != null)
                    hashCode = hashCode * 59 + this.NetworkComminglingTransactionEventList.GetHashCode();
                if (this.AffordabilityExpenseEventList != null)
                    hashCode = hashCode * 59 + this.AffordabilityExpenseEventList.GetHashCode();
                if (this.AffordabilityExpenseReversalEventList != null)
                    hashCode = hashCode * 59 + this.AffordabilityExpenseReversalEventList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
