/* 
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound
{
    /// <summary>
    /// LabelDownloadURL
    /// </summary>
    [DataContract]
    public partial class LabelDownloadURL : IEquatable<LabelDownloadURL>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LabelDownloadURL" /> class.
        /// </summary>
        /// <param name="downloadURL">URL to download the label for the package. Note: The URL will only be valid for 15 seconds.</param>
        public LabelDownloadURL(string downloadURL = default(string))
        {
            this.DownloadURL = downloadURL;
        }

        /// <summary>
        /// URL to download the label for the package. Note: The URL will only be valid for 15 seconds
        /// </summary>
        /// <value>URL to download the label for the package. Note: The URL will only be valid for 15 seconds</value>
        [DataMember(Name = "DownloadURL", EmitDefaultValue = false)]
        public string DownloadURL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LabelDownloadURL {\n");
            sb.Append("  DownloadURL: ").Append(DownloadURL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LabelDownloadURL);
        }

        /// <summary>
        /// Returns true if LabelDownloadURL instances are equal
        /// </summary>
        /// <param name="input">Instance of LabelDownloadURL to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LabelDownloadURL input)
        {
            if (input == null)
                return false;

            return
                (
                    this.DownloadURL == input.DownloadURL ||
                    (this.DownloadURL != null &&
                    this.DownloadURL.Equals(input.DownloadURL))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DownloadURL != null)
                    hashCode = hashCode * 59 + this.DownloadURL.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}